name: Java CI with Gradle

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - "README.md"
permissions:
  contents: read
  checks: write
  packages: write

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v3.1.0
      with: 
        dockerfile: Dockerfile

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
          
    - name: Run Tests
      run: ./gradlew test

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/reports/tests/test

    - name: Publish JUnit Report
      if: always()
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: 'build/test-results/test/TEST-*.xml'
        
  build:
    name: Build and Publish Docker Image
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/pilot-java-api:${{ github.sha }} .
    
    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}/pilot-java-api:${{ github.sha }}

